# Generated by Django 4.0.3 on 2022-04-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_Agrego_Columna_Descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='foto',
            field=models.ImageField(null=True, upload_to='multimedia'),
        ),
    ]
